//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/Examen.BE")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioCampaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float EstadoActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamTest.ServiceReference1.Marca[] MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarcaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnioCampania {
            get {
                return this.AnioCampaniaField;
            }
            set {
                if ((this.AnioCampaniaField.Equals(value) != true)) {
                    this.AnioCampaniaField = value;
                    this.RaisePropertyChanged("AnioCampania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSAP {
            get {
                return this.CodigoSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSAPField, value) != true)) {
                    this.CodigoSAPField = value;
                    this.RaisePropertyChanged("CodigoSAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoOferta {
            get {
                return this.CodigoTipoOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoOfertaField, value) != true)) {
                    this.CodigoTipoOfertaField = value;
                    this.RaisePropertyChanged("CodigoTipoOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuv {
            get {
                return this.CuvField;
            }
            set {
                if ((object.ReferenceEquals(this.CuvField, value) != true)) {
                    this.CuvField = value;
                    this.RaisePropertyChanged("Cuv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float EstadoActivo {
            get {
                return this.EstadoActivoField;
            }
            set {
                if ((this.EstadoActivoField.Equals(value) != true)) {
                    this.EstadoActivoField = value;
                    this.RaisePropertyChanged("EstadoActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamTest.ServiceReference1.Marca[] Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarcaID {
            get {
                return this.MarcaIDField;
            }
            set {
                if ((this.MarcaIDField.Equals(value) != true)) {
                    this.MarcaIDField = value;
                    this.RaisePropertyChanged("MarcaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://schemas.datacontract.org/2004/07/Examen.BE")]
    [System.SerializableAttribute()]
    public partial class Marca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarcaIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarcaID {
            get {
                return this.MarcaIDField;
            }
            set {
                if ((this.MarcaIDField.Equals(value) != true)) {
                    this.MarcaIDField = value;
                    this.RaisePropertyChanged("MarcaID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IExamenService")]
    public interface IExamenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenService/ListarProductos", ReplyAction="http://tempuri.org/IExamenService/ListarProductosResponse")]
        ExamTest.ServiceReference1.Producto[] ListarProductos(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamenService/ListarProductos", ReplyAction="http://tempuri.org/IExamenService/ListarProductosResponse")]
        System.Threading.Tasks.Task<ExamTest.ServiceReference1.Producto[]> ListarProductosAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExamenServiceChannel : ExamTest.ServiceReference1.IExamenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamenServiceClient : System.ServiceModel.ClientBase<ExamTest.ServiceReference1.IExamenService>, ExamTest.ServiceReference1.IExamenService {
        
        public ExamenServiceClient() {
        }
        
        public ExamenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExamTest.ServiceReference1.Producto[] ListarProductos(string nombre) {
            return base.Channel.ListarProductos(nombre);
        }
        
        public System.Threading.Tasks.Task<ExamTest.ServiceReference1.Producto[]> ListarProductosAsync(string nombre) {
            return base.Channel.ListarProductosAsync(nombre);
        }
    }
}
